//
//  UIColor+UIFontExtension.swift
//
//  Generated by Zeplin on 8/7/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	class var melon: UIColor {
		return UIColor(red: 252.0 / 255.0, green: 119.0 / 255.0, blue: 83.0 / 255.0, alpha: 1.0)
	}

	class var defaultTextColor: UIColor { 
		return UIColor(red: 31.0 / 255.0, green: 49.0 / 255.0, blue: 74.0 / 255.0, alpha: 1.0)
	}

	class var greenSuccess: UIColor {
		return UIColor(red: 64.0 / 255.0, green: 189.0 / 255.0, blue: 71.0 / 255.0, alpha: 1.0)
	}
    
    class var cornflower: UIColor {
        return UIColor(red: 102.0 / 255.0, green: 101.0 / 255.0, blue: 255.0 / 255.0, alpha: 1.0)
    }
    
    class var facebookBlue: UIColor {
        return UIColor(red: 101.0 / 255.0, green: 164.0 / 255.0, blue: 255.0 / 255.0, alpha: 1.0)
    }
    
    class var paleGrey: UIColor {
        return UIColor(red: 239.0 / 255.0, green: 241.0 / 255.0, blue: 245.0 / 255.0, alpha: 1.0)
    }
    
    class var stormyBlue: UIColor {
        return UIColor(red: 81.0 / 255.0, green: 117.0 / 255.0, blue: 157.0 / 255.0, alpha: 1.0)
    }
    
    class var skyBlue: UIColor {
        return UIColor(red: 101.0 / 255.0, green: 164.0 / 255.0, blue: 255.0 / 255.0, alpha: 1.0)
    }
    
    class var squash: UIColor {
        return UIColor(red: 245.0 / 255.0, green: 166.0 / 255.0, blue: 35.0 / 255.0, alpha: 1.0)
    }
    
    class var toxicGreen: UIColor {
        return UIColor(red: 53.0 / 255.0, green: 225.0 / 255.0, blue: 63.0 / 255.0, alpha: 1.0)
    }
    
    class var silver: UIColor {
        return UIColor(red: 213.0 / 255.0, green: 216.0 / 255.0, blue: 221.0 / 255.0, alpha: 1.0)
    }
    
    class var coolGrey: UIColor {
        return UIColor(red: 166.0 / 255.0, green: 173.0 / 255.0, blue: 183.0 / 255.0, alpha: 1.0)
    }

    class var lightGold: UIColor {
        return UIColor(red: 255.0 / 255.0, green: 215.0 / 255.0, blue: 80.0 / 255.0, alpha: 1.0)
    }
    
    class var salmon: UIColor {
        return UIColor(red: 255.0 / 255.0, green: 101.0 / 255.0, blue: 101.0 / 255.0, alpha: 1.0)
    }
}

// Text styles

extension UIFont {
    class func headerStyleFont() -> UIFont {
        return UIFont.systemFont(ofSize: 25.0, weight: UIFont.Weight.heavy)
    }
    
    class func optionStyleFont() -> UIFont {
        return UIFont.systemFont(ofSize: 20.0, weight: UIFont.Weight.bold)
    }
    
    class func normalTextStyleFont() -> UIFont {
        return UIFont.systemFont(ofSize: 19.0, weight: UIFont.Weight.regular)
    }
    
    class func buttonStyleFont() -> UIFont {
        return UIFont.systemFont(ofSize: 19.0, weight: UIFont.Weight.bold)
    }
    
    class func slideStyleFont() -> UIFont {
        return UIFont.systemFont(ofSize: 23.0, weight: .regular)
    }
}
